//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABB1Client.Lab1ExtrasService2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Lab1ExtrasService2.Extras2ServiceSoap")]
    public interface Extras2ServiceSoap {
        
        // CODEGEN: Generating message contract since element name FruitFinderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FruitFinder", ReplyAction="*")]
        LABB1Client.Lab1ExtrasService2.FruitFinderResponse FruitFinder(LABB1Client.Lab1ExtrasService2.FruitFinderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FruitFinder", ReplyAction="*")]
        System.Threading.Tasks.Task<LABB1Client.Lab1ExtrasService2.FruitFinderResponse> FruitFinderAsync(LABB1Client.Lab1ExtrasService2.FruitFinderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FruitFinderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FruitFinder", Namespace="http://tempuri.org/", Order=0)]
        public LABB1Client.Lab1ExtrasService2.FruitFinderRequestBody Body;
        
        public FruitFinderRequest() {
        }
        
        public FruitFinderRequest(LABB1Client.Lab1ExtrasService2.FruitFinderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FruitFinderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public char letterKey;
        
        public FruitFinderRequestBody() {
        }
        
        public FruitFinderRequestBody(char letterKey) {
            this.letterKey = letterKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FruitFinderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FruitFinderResponse", Namespace="http://tempuri.org/", Order=0)]
        public LABB1Client.Lab1ExtrasService2.FruitFinderResponseBody Body;
        
        public FruitFinderResponse() {
        }
        
        public FruitFinderResponse(LABB1Client.Lab1ExtrasService2.FruitFinderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FruitFinderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FruitFinderResult;
        
        public FruitFinderResponseBody() {
        }
        
        public FruitFinderResponseBody(string FruitFinderResult) {
            this.FruitFinderResult = FruitFinderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Extras2ServiceSoapChannel : LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Extras2ServiceSoapClient : System.ServiceModel.ClientBase<LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap>, LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap {
        
        public Extras2ServiceSoapClient() {
        }
        
        public Extras2ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Extras2ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Extras2ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Extras2ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LABB1Client.Lab1ExtrasService2.FruitFinderResponse LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap.FruitFinder(LABB1Client.Lab1ExtrasService2.FruitFinderRequest request) {
            return base.Channel.FruitFinder(request);
        }
        
        public string FruitFinder(char letterKey) {
            LABB1Client.Lab1ExtrasService2.FruitFinderRequest inValue = new LABB1Client.Lab1ExtrasService2.FruitFinderRequest();
            inValue.Body = new LABB1Client.Lab1ExtrasService2.FruitFinderRequestBody();
            inValue.Body.letterKey = letterKey;
            LABB1Client.Lab1ExtrasService2.FruitFinderResponse retVal = ((LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap)(this)).FruitFinder(inValue);
            return retVal.Body.FruitFinderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LABB1Client.Lab1ExtrasService2.FruitFinderResponse> LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap.FruitFinderAsync(LABB1Client.Lab1ExtrasService2.FruitFinderRequest request) {
            return base.Channel.FruitFinderAsync(request);
        }
        
        public System.Threading.Tasks.Task<LABB1Client.Lab1ExtrasService2.FruitFinderResponse> FruitFinderAsync(char letterKey) {
            LABB1Client.Lab1ExtrasService2.FruitFinderRequest inValue = new LABB1Client.Lab1ExtrasService2.FruitFinderRequest();
            inValue.Body = new LABB1Client.Lab1ExtrasService2.FruitFinderRequestBody();
            inValue.Body.letterKey = letterKey;
            return ((LABB1Client.Lab1ExtrasService2.Extras2ServiceSoap)(this)).FruitFinderAsync(inValue);
        }
    }
}
