//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABB1Client.Labb1Service1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Labb1Service1.Lab1Service1Soap")]
    public interface Lab1Service1Soap {
        
        // CODEGEN: Generating message contract since element name EstimatedWeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstimatedWeather", ReplyAction="*")]
        LABB1Client.Labb1Service1.EstimatedWeatherResponse EstimatedWeather(LABB1Client.Labb1Service1.EstimatedWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstimatedWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<LABB1Client.Labb1Service1.EstimatedWeatherResponse> EstimatedWeatherAsync(LABB1Client.Labb1Service1.EstimatedWeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstimatedWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstimatedWeather", Namespace="http://tempuri.org/", Order=0)]
        public LABB1Client.Labb1Service1.EstimatedWeatherRequestBody Body;
        
        public EstimatedWeatherRequest() {
        }
        
        public EstimatedWeatherRequest(LABB1Client.Labb1Service1.EstimatedWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EstimatedWeatherRequestBody {
        
        public EstimatedWeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstimatedWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstimatedWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public LABB1Client.Labb1Service1.EstimatedWeatherResponseBody Body;
        
        public EstimatedWeatherResponse() {
        }
        
        public EstimatedWeatherResponse(LABB1Client.Labb1Service1.EstimatedWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstimatedWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstimatedWeatherResult;
        
        public EstimatedWeatherResponseBody() {
        }
        
        public EstimatedWeatherResponseBody(string EstimatedWeatherResult) {
            this.EstimatedWeatherResult = EstimatedWeatherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Lab1Service1SoapChannel : LABB1Client.Labb1Service1.Lab1Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Lab1Service1SoapClient : System.ServiceModel.ClientBase<LABB1Client.Labb1Service1.Lab1Service1Soap>, LABB1Client.Labb1Service1.Lab1Service1Soap {
        
        public Lab1Service1SoapClient() {
        }
        
        public Lab1Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Lab1Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Lab1Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Lab1Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LABB1Client.Labb1Service1.EstimatedWeatherResponse LABB1Client.Labb1Service1.Lab1Service1Soap.EstimatedWeather(LABB1Client.Labb1Service1.EstimatedWeatherRequest request) {
            return base.Channel.EstimatedWeather(request);
        }
        
        public string EstimatedWeather() {
            LABB1Client.Labb1Service1.EstimatedWeatherRequest inValue = new LABB1Client.Labb1Service1.EstimatedWeatherRequest();
            inValue.Body = new LABB1Client.Labb1Service1.EstimatedWeatherRequestBody();
            LABB1Client.Labb1Service1.EstimatedWeatherResponse retVal = ((LABB1Client.Labb1Service1.Lab1Service1Soap)(this)).EstimatedWeather(inValue);
            return retVal.Body.EstimatedWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LABB1Client.Labb1Service1.EstimatedWeatherResponse> LABB1Client.Labb1Service1.Lab1Service1Soap.EstimatedWeatherAsync(LABB1Client.Labb1Service1.EstimatedWeatherRequest request) {
            return base.Channel.EstimatedWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<LABB1Client.Labb1Service1.EstimatedWeatherResponse> EstimatedWeatherAsync() {
            LABB1Client.Labb1Service1.EstimatedWeatherRequest inValue = new LABB1Client.Labb1Service1.EstimatedWeatherRequest();
            inValue.Body = new LABB1Client.Labb1Service1.EstimatedWeatherRequestBody();
            return ((LABB1Client.Labb1Service1.Lab1Service1Soap)(this)).EstimatedWeatherAsync(inValue);
        }
    }
}
