//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NrthWndService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipper", Namespace="http://schemas.datacontract.org/2004/07/NrthWndService")]
    public partial class Shipper : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompanyNameField;
        
        private int IDField;
        
        private string PhoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Shippery", ConfigurationName="IShipperservice")]
public interface IShipperservice
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Shippery/IShipperservice/GetShipper", ReplyAction="http://Shippery/IShipperservice/GetShipperResponse")]
    NrthWndService.Shipper GetShipper(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Shippery/IShipperservice/GetShipper", ReplyAction="http://Shippery/IShipperservice/GetShipperResponse")]
    System.Threading.Tasks.Task<NrthWndService.Shipper> GetShipperAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Shippery/IShipperservice/SaveShipper", ReplyAction="http://Shippery/IShipperservice/SaveShipperResponse")]
    void SaveShipper(NrthWndService.Shipper shipper);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Shippery/IShipperservice/SaveShipper", ReplyAction="http://Shippery/IShipperservice/SaveShipperResponse")]
    System.Threading.Tasks.Task SaveShipperAsync(NrthWndService.Shipper shipper);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IShipperserviceChannel : IShipperservice, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShipperserviceClient : System.ServiceModel.ClientBase<IShipperservice>, IShipperservice
{
    
    public ShipperserviceClient()
    {
    }
    
    public ShipperserviceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShipperserviceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public NrthWndService.Shipper GetShipper(int id)
    {
        return base.Channel.GetShipper(id);
    }
    
    public System.Threading.Tasks.Task<NrthWndService.Shipper> GetShipperAsync(int id)
    {
        return base.Channel.GetShipperAsync(id);
    }
    
    public void SaveShipper(NrthWndService.Shipper shipper)
    {
        base.Channel.SaveShipper(shipper);
    }
    
    public System.Threading.Tasks.Task SaveShipperAsync(NrthWndService.Shipper shipper)
    {
        return base.Channel.SaveShipperAsync(shipper);
    }
}
