//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://AgeCheckerService", ConfigurationName="IAgeChecker")]
public interface IAgeChecker
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://AgeCheckerService/IAgeChecker/AgeInYears", ReplyAction="http://AgeCheckerService/IAgeChecker/AgeInYearsResponse")]
    double AgeInYears(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://AgeCheckerService/IAgeChecker/AgeInYears", ReplyAction="http://AgeCheckerService/IAgeChecker/AgeInYearsResponse")]
    System.Threading.Tasks.Task<double> AgeInYearsAsync(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://AgeCheckerService/IAgeChecker/AgeInDays", ReplyAction="http://AgeCheckerService/IAgeChecker/AgeInDaysResponse")]
    double AgeInDays(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://AgeCheckerService/IAgeChecker/AgeInDays", ReplyAction="http://AgeCheckerService/IAgeChecker/AgeInDaysResponse")]
    System.Threading.Tasks.Task<double> AgeInDaysAsync(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://AgeCheckerService/IAgeChecker/AgeInHours", ReplyAction="http://AgeCheckerService/IAgeChecker/AgeInHoursResponse")]
    double AgeInHours(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://AgeCheckerService/IAgeChecker/AgeInHours", ReplyAction="http://AgeCheckerService/IAgeChecker/AgeInHoursResponse")]
    System.Threading.Tasks.Task<double> AgeInHoursAsync(System.DateTime date);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAgeCheckerChannel : IAgeChecker, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AgeCheckerClient : System.ServiceModel.ClientBase<IAgeChecker>, IAgeChecker
{
    
    public AgeCheckerClient()
    {
    }
    
    public AgeCheckerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AgeCheckerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AgeCheckerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AgeCheckerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double AgeInYears(System.DateTime date)
    {
        return base.Channel.AgeInYears(date);
    }
    
    public System.Threading.Tasks.Task<double> AgeInYearsAsync(System.DateTime date)
    {
        return base.Channel.AgeInYearsAsync(date);
    }
    
    public double AgeInDays(System.DateTime date)
    {
        return base.Channel.AgeInDays(date);
    }
    
    public System.Threading.Tasks.Task<double> AgeInDaysAsync(System.DateTime date)
    {
        return base.Channel.AgeInDaysAsync(date);
    }
    
    public double AgeInHours(System.DateTime date)
    {
        return base.Channel.AgeInHours(date);
    }
    
    public System.Threading.Tasks.Task<double> AgeInHoursAsync(System.DateTime date)
    {
        return base.Channel.AgeInHoursAsync(date);
    }
}
