//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://BMIService", ConfigurationName="IBMICounter")]
public interface IBMICounter
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://BMIService/IBMICounter/CalculateBMI", ReplyAction="http://BMIService/IBMICounter/CalculateBMIResponse")]
    float CalculateBMI(float weight, float height);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://BMIService/IBMICounter/CalculateBMI", ReplyAction="http://BMIService/IBMICounter/CalculateBMIResponse")]
    System.Threading.Tasks.Task<float> CalculateBMIAsync(float weight, float height);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBMICounterChannel : IBMICounter, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BMICounterClient : System.ServiceModel.ClientBase<IBMICounter>, IBMICounter
{
    
    public BMICounterClient()
    {
    }
    
    public BMICounterClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BMICounterClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMICounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BMICounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public float CalculateBMI(float weight, float height)
    {
        return base.Channel.CalculateBMI(weight, height);
    }
    
    public System.Threading.Tasks.Task<float> CalculateBMIAsync(float weight, float height)
    {
        return base.Channel.CalculateBMIAsync(weight, height);
    }
}
