//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABB1Client.Lab1Service5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Lab1Service5.Lab1Service5Soap")]
    public interface Lab1Service5Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateFinder", ReplyAction="*")]
        LABB1Client.Lab1Service5.DateFinderResponse DateFinder(LABB1Client.Lab1Service5.DateFinderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateFinder", ReplyAction="*")]
        System.Threading.Tasks.Task<LABB1Client.Lab1Service5.DateFinderResponse> DateFinderAsync(LABB1Client.Lab1Service5.DateFinderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateFinderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateFinder", Namespace="http://tempuri.org/", Order=0)]
        public LABB1Client.Lab1Service5.DateFinderRequestBody Body;
        
        public DateFinderRequest() {
        }
        
        public DateFinderRequest(LABB1Client.Lab1Service5.DateFinderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DateFinderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public DateFinderRequestBody() {
        }
        
        public DateFinderRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateFinderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateFinderResponse", Namespace="http://tempuri.org/", Order=0)]
        public LABB1Client.Lab1Service5.DateFinderResponseBody Body;
        
        public DateFinderResponse() {
        }
        
        public DateFinderResponse(LABB1Client.Lab1Service5.DateFinderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DateFinderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DateFinderResult;
        
        public DateFinderResponseBody() {
        }
        
        public DateFinderResponseBody(string DateFinderResult) {
            this.DateFinderResult = DateFinderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Lab1Service5SoapChannel : LABB1Client.Lab1Service5.Lab1Service5Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Lab1Service5SoapClient : System.ServiceModel.ClientBase<LABB1Client.Lab1Service5.Lab1Service5Soap>, LABB1Client.Lab1Service5.Lab1Service5Soap {
        
        public Lab1Service5SoapClient() {
        }
        
        public Lab1Service5SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Lab1Service5SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Lab1Service5SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Lab1Service5SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LABB1Client.Lab1Service5.DateFinderResponse LABB1Client.Lab1Service5.Lab1Service5Soap.DateFinder(LABB1Client.Lab1Service5.DateFinderRequest request) {
            return base.Channel.DateFinder(request);
        }
        
        public string DateFinder(string name) {
            LABB1Client.Lab1Service5.DateFinderRequest inValue = new LABB1Client.Lab1Service5.DateFinderRequest();
            inValue.Body = new LABB1Client.Lab1Service5.DateFinderRequestBody();
            inValue.Body.name = name;
            LABB1Client.Lab1Service5.DateFinderResponse retVal = ((LABB1Client.Lab1Service5.Lab1Service5Soap)(this)).DateFinder(inValue);
            return retVal.Body.DateFinderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LABB1Client.Lab1Service5.DateFinderResponse> LABB1Client.Lab1Service5.Lab1Service5Soap.DateFinderAsync(LABB1Client.Lab1Service5.DateFinderRequest request) {
            return base.Channel.DateFinderAsync(request);
        }
        
        public System.Threading.Tasks.Task<LABB1Client.Lab1Service5.DateFinderResponse> DateFinderAsync(string name) {
            LABB1Client.Lab1Service5.DateFinderRequest inValue = new LABB1Client.Lab1Service5.DateFinderRequest();
            inValue.Body = new LABB1Client.Lab1Service5.DateFinderRequestBody();
            inValue.Body.name = name;
            return ((LABB1Client.Lab1Service5.Lab1Service5Soap)(this)).DateFinderAsync(inValue);
        }
    }
}
