//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://CharacterGeneratorService", ClrNamespace="charactergeneratorservice")]

namespace charactergeneratorservice
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://CharacterGeneratorService")]
    public partial class Character : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] AbilitiesField;
        
        private int AgeField;
        
        private string ClassTypeField;
        
        private double HealthField;
        
        private int LevelField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Abilities
        {
            get
            {
                return this.AbilitiesField;
            }
            set
            {
                this.AbilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassType
        {
            get
            {
                return this.ClassTypeField;
            }
            set
            {
                this.ClassTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Health
        {
            get
            {
                return this.HealthField;
            }
            set
            {
                this.HealthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://CharacterGeneratorService", ConfigurationName="ICharacterCreator")]
public interface ICharacterCreator
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://CharacterGeneratorService/ICharacterCreator/GenerateCharacter", ReplyAction="http://CharacterGeneratorService/ICharacterCreator/GenerateCharacterResponse")]
    charactergeneratorservice.Character GenerateCharacter(string name, string classType, int age);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://CharacterGeneratorService/ICharacterCreator/GenerateCharacter", ReplyAction="http://CharacterGeneratorService/ICharacterCreator/GenerateCharacterResponse")]
    System.Threading.Tasks.Task<charactergeneratorservice.Character> GenerateCharacterAsync(string name, string classType, int age);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://CharacterGeneratorService/ICharacterCreator/GenerateAblities", ReplyAction="http://CharacterGeneratorService/ICharacterCreator/GenerateAblitiesResponse")]
    string[] GenerateAblities(string classType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://CharacterGeneratorService/ICharacterCreator/GenerateAblities", ReplyAction="http://CharacterGeneratorService/ICharacterCreator/GenerateAblitiesResponse")]
    System.Threading.Tasks.Task<string[]> GenerateAblitiesAsync(string classType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://CharacterGeneratorService/ICharacterCreator/CalculateHealth", ReplyAction="http://CharacterGeneratorService/ICharacterCreator/CalculateHealthResponse")]
    double CalculateHealth(int age, int level);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://CharacterGeneratorService/ICharacterCreator/CalculateHealth", ReplyAction="http://CharacterGeneratorService/ICharacterCreator/CalculateHealthResponse")]
    System.Threading.Tasks.Task<double> CalculateHealthAsync(int age, int level);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICharacterCreatorChannel : ICharacterCreator, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CharacterCreatorClient : System.ServiceModel.ClientBase<ICharacterCreator>, ICharacterCreator
{
    
    public CharacterCreatorClient()
    {
    }
    
    public CharacterCreatorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CharacterCreatorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CharacterCreatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CharacterCreatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public charactergeneratorservice.Character GenerateCharacter(string name, string classType, int age)
    {
        return base.Channel.GenerateCharacter(name, classType, age);
    }
    
    public System.Threading.Tasks.Task<charactergeneratorservice.Character> GenerateCharacterAsync(string name, string classType, int age)
    {
        return base.Channel.GenerateCharacterAsync(name, classType, age);
    }
    
    public string[] GenerateAblities(string classType)
    {
        return base.Channel.GenerateAblities(classType);
    }
    
    public System.Threading.Tasks.Task<string[]> GenerateAblitiesAsync(string classType)
    {
        return base.Channel.GenerateAblitiesAsync(classType);
    }
    
    public double CalculateHealth(int age, int level)
    {
        return base.Channel.CalculateHealth(age, level);
    }
    
    public System.Threading.Tasks.Task<double> CalculateHealthAsync(int age, int level)
    {
        return base.Channel.CalculateHealthAsync(age, level);
    }
}
