//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="DaysUntilNextThousandDays", ConfigurationName="INextThousandDays")]
public interface INextThousandDays
{
    
    [System.ServiceModel.OperationContractAttribute(Action="DaysUntilNextThousandDays/INextThousandDays/DaysToGo", ReplyAction="DaysUntilNextThousandDays/INextThousandDays/DaysToGoResponse")]
    System.DateTime DaysToGo(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="DaysUntilNextThousandDays/INextThousandDays/DaysToGo", ReplyAction="DaysUntilNextThousandDays/INextThousandDays/DaysToGoResponse")]
    System.Threading.Tasks.Task<System.DateTime> DaysToGoAsync(System.DateTime date);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INextThousandDaysChannel : INextThousandDays, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NextThousandDaysClient : System.ServiceModel.ClientBase<INextThousandDays>, INextThousandDays
{
    
    public NextThousandDaysClient()
    {
    }
    
    public NextThousandDaysClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NextThousandDaysClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NextThousandDaysClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NextThousandDaysClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime DaysToGo(System.DateTime date)
    {
        return base.Channel.DaysToGo(date);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> DaysToGoAsync(System.DateTime date)
    {
        return base.Channel.DaysToGoAsync(date);
    }
}
